const all_damage_types = [
    {"name": "Physical", "rank": 0, "type": "direct", "resistance": "Physical", "include_damage": true, "retaliation_include_damage": true},
    {"name": "Pierce", "rank": 1, "type": "direct", "resistance": "Pierce", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Fire", "rank": 2, "type": "direct", "resistance": "Fire", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Cold", "rank": 3, "type": "direct", "resistance": "Cold", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Lightning", "rank": 4, "type": "direct", "resistance": "Lightning", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Acid", "rank": 5, "type": "direct", "resistance": "Acid", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Vitality", "rank": 6, "type": "direct", "resistance": "Vitality", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Aether", "rank": 7, "type": "direct", "resistance": "Aether", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Chaos", "rank": 8, "type": "direct", "resistance": "Chaos", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Elemental", "rank": 9, "type": "direct", "resistance": "Elemental", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Internal Trauma", "rank": 10, "type": "dot", "resistance": "Physical", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Bleeding", "rank": 11, "type": "dot", "resistance": "Bleeding", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Burn", "rank": 12, "type": "dot", "resistance": "Fire", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Frostburn", "rank": 13, "type": "dot", "resistance": "Cold", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Electrocute", "rank": 14, "type": "dot", "resistance": "Lightning", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Poison", "rank": 15, "type": "dot", "resistance": "Acid", "include_damage": true, "retaliation_include_damage": false},
    {"name": "Vitality Decay", "rank": 16, "type": "dot", "resistance": "Vitality", "include_damage": false, "retaliation_include_damage": false},
];

